import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar";
import { Providers } from "./providers";
import { cookies } from "next/headers";
import { createClient } from "@/lib/supabase/server";
import AuthenticationPage from "@/components/Authenticate";

const space_Grotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const supabase = createClient(cookieStore);

  const { data } = await supabase.auth.getUser();
  console.log(data);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={space_Grotesk.className}>
        <Providers>
          {data.user === null ? (
            <AuthenticationPage />
          ) : (
            <>
              <Navbar />
              <div className="max-w-5xl mx-auto h-[calc(100vh_-_65px)] bg-card py-4 px-2">
                {children}
              </div>
              <Toaster position="top-center" />
            </>
          )}
        </Providers>
      </body>
    </html>
  );
}
